//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma_Estudiantil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno_Tarea
    {
        public int id { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public Nullable<int> idTarea { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual tarea tarea { get; set; }
    }
}
