//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma_Estudiantil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nota()
        {
            this.Notas_Periodos = new HashSet<Notas_Periodos>();
        }
    
        public int idNotas { get; set; }
        public Nullable<double> nota1 { get; set; }
        public Nullable<double> nota2 { get; set; }
        public Nullable<double> nota3 { get; set; }
        public Nullable<double> nota4 { get; set; }
        public int idAsignatura { get; set; }
        public int idAlumno { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual Asignatura Asignatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notas_Periodos> Notas_Periodos { get; set; }
    }
}
